# Generated by Django 3.1.7 on 2021-04-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsy_turvy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='perma_cookie',
            field=models.CharField(default='PERMA COOKIE', max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
