# Generated by Django 3.1.7 on 2021-04-06 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('wins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('won', models.BooleanField(default=False)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to='topsy_turvy.player')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='topsy_turvy.player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topsy_turvy.player')),
            ],
        ),
    ]
